### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bofh69** [bofh69/sm2ss#1]
- [x] Add reuse and pylint actions & badges.
- [x] Translate spool info to a filename through jinja templates (templates-SLICER/filename.template ?).
- [x] Use gc based on the filename instead of filament id.
- [x] Don't update the filament when the template renders to the same value.
- [x] Monitor filament changes (they currently don't trigger spool changes).
- [x] Handle file updates by writing to a temporary file and move over the old file (only if they differ).
- [x] Monitor manufacturer changes (they currently don't trigger spool changes).
- [x] Add OrcaSlicer templates.

**Comment by bofh69** [comment]
- [x] Read template files from ~/.config/spoolman2slicer.
- [x] Copy the template files to ~/.config/spoolman2slicer if they are missing.
- [x] Add a Makefile with fmt/lint/reuse targets like nfc2klipper has.

**Comment by bofh69** [comment]
* [ ] add info/example about calculating fields in templates, ie cost/g from spool price.
* [x] Make a program to create templates from existing filament config.
